TestShell/TestShell/TestShell.vcxproj, TestShell/TestShell/TestShell.vcxproj.filters, TestShell/TestShell/executor.h, TestShell/TestShell/mockExecutor.cpp, TestShell/TestShell/ssdExecutor.cpp
shell 에서 mock 구현을 위한 executor interface 지원
=> [shell][feature] support mockExecutor

TestShell/TestShell/testShell.cpp, TestShell/TestShell/test_read.cpp
1. read : Mock 기반으로 임의의 8자리 알파벳으로 스트링을 구성하고 이대로 쓰여져 있는지를 검증하였습니다.
2. fullread : 0~99번지까지 read 하는 동안 "ERROR" 를 리턴하는 경우가 있는지 검증하였습니다.
=> User Level 의 read 와 fullread 를 구현했습니다.

TestShell/TestShell/test_ShellCmdParser.cpp
=> [parser][feature] test shellcmd fixture

TestShell/TestShell/TestShell.vcxproj, TestShell/TestShell/TestShell.vcxproj.filters, TestShell/TestShell/shellCmdParser.cpp, TestShell/TestShell/shellCmdParser.h, TestShell/TestShell/testShellCmdInterface.h, TestShell/TestShell/testShellCmdRead.h, TestShell/TestShell/testShellCmdWrite.h, TestShell/TestShell/test_ShellCmdParser.cpp
shell CMD paring read TC 및 구현입니다
리뷰 부탁드립니다
=> shell CMD paring read TC 및 구현입니다

SSDSimulator/SSDSimulator/SSDSimulator.vcxproj, SSDSimulator/SSDSimulator/ssdCmdParser.cpp, SSDSimulator/SSDSimulator/ssdCmdRead.cpp, SSDSimulator/SSDSimulator/ssdCmdRead.h, SSDSimulator/SSDSimulator/test_ssdCmdRead.cpp
- invalid address check 하는 test 및 코드 구현하였습니다.
- long type을 unsigned int로 변경했습니다.
=> SSD Read - invalid address check

SSDSimulator/SSDSimulator/ssdCmdRead.cpp, SSDSimulator/SSDSimulator/ssdCmdRead.h, SSDSimulator/SSDSimulator/ssdInterface.h, SSDSimulator/SSDSimulator/test_ssdCmdRead.cpp
- ssd_nand.txt에 있는 내용을 잘 읽어오는지 test합니다.
=> SSD Read Data Valid 체크하는 함수 테스트 및 구현입니다.

SSDSimulator/SSDSimulator/ssdCmdWrite.cpp, SSDSimulator/SSDSimulator/ssdCmdWrite.h, SSDSimulator/SSDSimulator/ssdInterface.h, SSDSimulator/SSDSimulator/test_ssdCmdWrite.cpp
빌드 테스트 및 UT test 확인
UT 중 write data integrity 확인하는 테스트는 임시 주석처리 --> Read 구현 완료 후 통합하여 테스트 예정
=> [refactoring] Write UT test 및 ssdWriteCmd class 리팩토링 (Read 스타일에 맞춤)

SSDSimulator/SSDSimulator/ssdCmdParser.cpp, SSDSimulator/SSDSimulator/ssdCmdRead.cpp, SSDSimulator/SSDSimulator/ssdCmdWrite.cpp, SSDSimulator/SSDSimulator/ssdCmdWrite.h, SSDSimulator/SSDSimulator/test_ssdCmdWrite.cpp
1) Refactored ssdCmdWrite to singleton
2) uncommeted ssd read in write unit test
3) fixed nand read to clear internal buffer if data is already there
=> Write singleton으로 수정 외

TestShell/TestShell/shellCmdParser.cpp, TestShell/TestShell/testShellCmdInterface.h, TestShell/TestShell/test_ShellCmdParser.cpp
shell cmd parser refactoring 리뷰 부탁드립니다
=> [parser][refactor] shell cmd and test code refactoring

SSDSimulator/SSDSimulator/ssdCmdRead.cpp, SSDSimulator/SSDSimulator/ssdCmdRead.h, SSDSimulator/SSDSimulator/test_ssdCmdRead.cpp, SSDSimulator/SSDSimulator/test_ssdCmdWrite.cpp
input file이 없을 때 모든 주소의 데이터를 0x00000000으로 채우고 파일을 생성하도록 수정하였습니다.
추가로 리팩토링 진행했어요
=> input file이 없을 때 모든 주소의 데이터를 0x00000000으로 채우기

.gitignore
=> === add gitignore to ssd_output

SSDSimulator/SSDSimulator/ssdInterface.h, SSDSimulator/SSDSimulator/ssdSimulator.h
NAND Data txt 파일 만들어주는 init 함수 입니다.
=> SSD Simulator 내 NAND Data 파일 init 추가 

SSDSimulator/SSDSimulator/main.cpp
SSD main 함수 구현입니다.
local 에서 read, write 체크 완료했습니다
다만 ERROR는 출력 안되는데, 이후 SSD에서 구현 필요해보이네요
=> [ssd][feature] implement ssd main

SSDSimulator/SSDSimulator/ssdCmdWrite.cpp, SSDSimulator/SSDSimulator/ssdCmdWrite.h
SsdWriteCmd class 내 불필요한 함수 제거
- SsdSimulator로 이동됨
=> [ssd][refactoring] removed redundant code in ssdWriteCmd class

SSDSimulator/SSDSimulator/IOManager.h, SSDSimulator/SSDSimulator/ssdCmdError.cpp, SSDSimulator/SSDSimulator/ssdSimulator.h, SSDSimulator/SSDSimulator/test_ssdCmdRead.cpp, SSDSimulator/SSDSimulator/test_ssdCmdWrite.cpp
SSD Sim에 모두 통합 해 놓았던 기능들 중 Input/Output 관련 파일들을 분리하였습니다.
=> [refactor] Separate IOManager Class

SSDSimulator/SSDSimulator/IOManager.h, SSDSimulator/SSDSimulator/test_ssdCmdErase.cpp, SSDSimulator/SSDSimulator/test_ssdCmdRead.cpp
[refactor] Read output 양식을 0x00000000으로 나오도록 변경하였습니다.
추가적으로 Read 및 Erase TC에서 output확인하는 부분을 보강하였습니다.
=> [refactor] Read output 양식을 0x00000000으로 나오도록 변경 및 TC 보강

SSDSimulator/SSDSimulator/cmdBuffer.cpp, SSDSimulator/SSDSimulator/main.cpp, SSDSimulator/SSDSimulator/test_cmdBuffer.cpp
=> [feature] cmd flush tc and fix flush bug

SSDSimulator/SSDSimulator/cmdBuffer.cpp, SSDSimulator/SSDSimulator/cmdBuffer.h, SSDSimulator/SSDSimulator/test_cmdBuffer.cpp
CmdBuffer UT Fixture 내 구조체 NiceMock으로 변경
=> [ssd][fix] fix for unit test fail

SSDSimulator/SSDSimulator/SSDSimulator.vcxproj, SSDSimulator/SSDSimulator/cmdBuffer.cpp, SSDSimulator/SSDSimulator/cmdBuffer.h, SSDSimulator/SSDSimulator/test_cmdBuffer.cpp
cmdQ와 resultQ 이름을 좀 더 명확하게 변경하였고,
addBufferAndGetCmdToRun에서 buffering 할 commad 여부 체크 함수 따로 추출하였습니다.
=> [refactor] Change Q name of CmdBuffer and extract function

SSDSimulator/SSDSimulator/SSDSimulator.vcxproj.filters
=> [ssd][minor] UT 파일들 "테스트 파일"필터로 이동

SSDSimulator/SSDSimulator/IOManager.cpp, SSDSimulator/SSDSimulator/IOManager.h, SSDSimulator/SSDSimulator/ssdSimulator.cpp, SSDSimulator/SSDSimulator/test_ssdCmdWrite.cpp
SSD Write시 output.txt에 ""쓰도록 수정 하였습니다
=> [ssd][fix] Fixed SSD write to write "" to output.txt upon success

TestShell/TestShell/shellCmdErase.cpp, TestShell/TestShell/shellCmdError.cpp, TestShell/TestShell/shellCmdFlush.cpp, TestShell/TestShell/shellCmdHelp.cpp, TestShell/TestShell/shellCmdInvalid.cpp, TestShell/TestShell/shellCmdRead.cpp, TestShell/TestShell/shellCmdTestScript.cpp, TestShell/TestShell/shellCmdWrite.cpp, TestShell/TestShell/testShellCmd.h, TestShell/TestShell/testShellCmdInterface.h
return type을 bool (성공/실패) 로 바꿔, runner에서 성공여부 확인을 위한 수정입니다~
=> [runner][feature] change cmd run return type to bool

SSDSimulator/SSDSimulator/cmdBuffer.cpp, SSDSimulator/SSDSimulator/ssdCmdParser.cpp, SSDSimulator/SSDSimulator/test_cmdBuffer.cpp
1. UT 추가 
2. cmdQ 덜찼을때 empty로 채워서 내리는 부분 같이 구현
UT 패스 확인 그러나 리팩토링 필요
=> [ssd][feature] commmand queue 내 커맨드들을 buffer 파일로 업데이트 하는 함수 구현

SSDSimulator/SSDSimulator/ssdCmdRead.cpp, SSDSimulator/SSDSimulator/ssdCmdRead.h, SSDSimulator/SSDSimulator/test_ssdCmdRead.cpp
이미 CommandBuffer에서 저장된 값을 읽었을 때,
ssd simulator 접근 없이 read 하기 위한 cmd 구현입니다
=> [cmdBuffer][feature] implement bufferedRead Cmd

TestShell/TestShell/latest.txt, TestShell/TestShell/shell.cpp, TestShell/TestShell/shellCmdParser.cpp, TestShell/TestShell/shellCmdParser.h, TestShell/TestShell/test_ShellCmdParser.cpp
shell commad paser 리팩토링 (smart pointer, 함수 추상황) 수정사항입니다.
어떤 변경 사항이 있나요?
- [ v] 코드 리팩토링
PR이 다음 요구 사항을 충족하는지 확인하세요.
- [ v] 변경 사항에 대한 유닛 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [ v] 빌드 테스트를 했습니다.
=> [parser][refactor] adding smart point of shell command parser

SSDSimulator/SSDSimulator/cmdBuffer.cpp, SSDSimulator/SSDSimulator/cmdBuffer.h
어떤 변경 사항이 있나요?
PR이 다음 요구 사항을 충족하는지 확인하세요.
=> [refactor] rename parameter
